FROM python:3.10-slim

RUN apt-get update && apt-get install python3-pip -y

COPY ./requirements2.txt /app/requirements2.txt

WORKDIR /app/

RUN pip install -r requirements2.txt

COPY api.py pre_processing.py data_ingestion.py kpi.py ./

COPY stop_words.csv subset.csv lda_model lda_model.state lda_model.id2word lda_model.expElogbeta.npy ./

CMD ["uvicorn","api:app","--host","0.0.0.0","--port","8000"]