FROM python:3.10-slim

RUN apt-get update && apt-get install -y python3-pip

COPY ./requirements.txt /app/requirements.txt

WORKDIR /app

RUN pip install -r requirements.txt

COPY ./api_modules ./api_modules
COPY api.py ./

COPY ./python_code ./python_code

COPY stop_words.csv subset.csv lda_model lda_model.state lda_model.id2word lda_model.expElogbeta.npy ./

CMD ["uvicorn", "api:app", "--host", "0.0.0.0", "--port", "8002"]
