FROM python:3.10-slim

RUN apt-get update && apt-get install python3-pip -y

COPY ./requirements.txt /app/requirements.txt

WORKDIR /app/

RUN pip install -r requirements.txt

COPY ./db/database_creation.py ./

COPY ./db/CI_newspaper_subcorpora ./CI_newspaper_subcorpora

CMD ["python","database_creation.py"]
