FROM python:3.10-slim

RUN apt-get update && apt-get install python3-pip -y

COPY ./requirements.txt /app/requirements.txt

WORKDIR /app/

RUN pip install -r requirements.txt

COPY api.py pre_processing.py data_ingestion.py kpi.py ./

COPY stop_words.csv subset.csv lda_model ./

COPY ./CI_newspaper_subcorpora ./CI_newspaper_subcorpora

CMD ["uvicorn","api:app","--host","0.0.0.0","--port","8000"]