name: Test

on:
  push:
    branches:
    - refactor_mlla


jobs:
  docker:
    timeout-minutes: 10
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: Start containers
      run: docker-compose -f "docker-compose.yml" up -d --build

    - name: Set up Python
      uses: actions/setup-python@master
      with:
        python-version: "3.10"

    - name: Install pytest and flake8
      run: |
        pip install pytest
        pip install requests

    - name: Run tests
      run: |
        pytest

    - name: Stop containers
      if: always()
      run: docker-compose -f "docker-compose.yml" down